-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN     "posteddate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Review" ADD COLUMN     "posteddate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
